using UnityEngine;

namespace MoonProject.Gameplay
{
    /// <summary>
    /// The SoftGlow materials gameplay effects draw with, generated by the Gameplay/Materials builder
    /// (Generated/Gameplay/Materials). Runtime code only reads it.
    /// </summary>
    public sealed class GameplayVisuals : ScriptableObject
    {
        [Tooltip("Expanding sonar ring on the ground (TechGlow, additive).")]
        [SerializeField] private Material _sonarRing;

        [Tooltip("Ground ring at an answered relic site (TechGlow, additive).")]
        [SerializeField] private Material _siteRing;

        [Tooltip("Light pillar over an answered site, seen from afar (TechGlow, additive, rising bands).")]
        [SerializeField] private Material _sitePillar;

        [Tooltip("Tractor beam cone from 07's eye (TechGlow, additive, flowing bands).")]
        [SerializeField] private Material _tractorBeam;

        [Tooltip("Tether line (TechGlow, additive, flowing bands).")]
        [SerializeField] private Material _tetherBeam;

        [Tooltip("Scrap pickup flash (TechGlow, additive, fresnel ball).")]
        [SerializeField] private Material _flash;

        [Tooltip("Relic highlight halo (TechGlow, additive, inverted hull with fresnel).")]
        [SerializeField] private Material _relicHalo;

        [Tooltip("Swirling dust around an excavation (dust lavender, soft premultiplied sprites).")]
        [SerializeField] private Material _dust;

        [Tooltip("Warm ground rings: tower pad, shelf slot hint, signal bloom (WarmLamp, additive).")]
        [SerializeField] private Material _warmRing;

        [Tooltip("Warm glow ball: radio tower beacon (WarmLamp, additive, fresnel).")]
        [SerializeField] private Material _warmGlow;

        [Tooltip("Camera-facing glints over distant scrap (Glint shader, TechGlow).")]
        [SerializeField] private Material _scrapGlint;

        [Tooltip("Camera-facing glints over a friend's missing parts (Glint shader, WarmLamp amber).")]
        [SerializeField] private Material _partGlint;

        [Tooltip("Light pillar over a broken friend that answered (WarmLamp, additive, rising bands).")]
        [SerializeField] private Material _friendPillar;

        public Material SonarRing => _sonarRing;
        public Material SiteRing => _siteRing;
        public Material SitePillar => _sitePillar;
        public Material TractorBeam => _tractorBeam;
        public Material TetherBeam => _tetherBeam;
        public Material Flash => _flash;
        public Material RelicHalo => _relicHalo;
        public Material Dust => _dust;
        public Material WarmRing => _warmRing;
        public Material WarmGlow => _warmGlow;
        public Material ScrapGlint => _scrapGlint;
        public Material PartGlint => _partGlint;
        public Material FriendPillar => _friendPillar;

        /// <summary>Null when every material is assigned, else the first missing one.</summary>
        public string Validate()
        {
            return _sonarRing == null ? "sonar ring material is missing"
                : _siteRing == null ? "site ring material is missing"
                : _sitePillar == null ? "site pillar material is missing"
                : _tractorBeam == null ? "tractor beam material is missing"
                : _tetherBeam == null ? "tether beam material is missing"
                : _flash == null ? "flash material is missing"
                : _relicHalo == null ? "relic halo material is missing"
                : _dust == null ? "dust material is missing"
                : _warmRing == null ? "warm ring material is missing"
                : _warmGlow == null ? "warm glow material is missing"
                : _scrapGlint == null ? "scrap glint material is missing"
                : _partGlint == null ? "part glint material is missing"
                : _friendPillar == null ? "friend pillar material is missing"
                : null;
        }

        internal void Populate(Material sonarRing, Material siteRing, Material sitePillar, Material tractorBeam,
            Material tetherBeam, Material flash, Material relicHalo, Material dust, Material warmRing,
            Material warmGlow, Material scrapGlint, Material partGlint, Material friendPillar)
        {
            _sonarRing = sonarRing;
            _siteRing = siteRing;
            _sitePillar = sitePillar;
            _tractorBeam = tractorBeam;
            _tetherBeam = tetherBeam;
            _flash = flash;
            _relicHalo = relicHalo;
            _dust = dust;
            _warmRing = warmRing;
            _warmGlow = warmGlow;
            _scrapGlint = scrapGlint;
            _partGlint = partGlint;
            _friendPillar = friendPillar;
        }
    }
}
