using System.Globalization;
using System.Text;
using UnityEngine;
using MoonProject.Art;

namespace MoonProject.UI.Editor
{
    /// <summary>
    /// The UI colour tokens, each a palette swatch at an opacity, written as USS custom properties on :root so every
    /// stylesheet reads colours from the art palette (MoonProject.Art.Palette) and never from a hex literal.
    /// </summary>
    internal static class ThemeTokens
    {
        private static readonly Token[] Tokens =
        {
            new Token("--moon-sky-top", PaletteSwatch.SkyTop, 1f),
            new Token("--moon-sky-horizon", PaletteSwatch.SkyHorizon, 1f),
            new Token("--moon-warm-lamp", PaletteSwatch.WarmLamp, 1f),
            new Token("--moon-warm-accent", PaletteSwatch.WarmAccent, 1f),
            new Token("--moon-cream", PaletteSwatch.Cream, 1f),
            new Token("--moon-honey", PaletteSwatch.Honey, 1f),
            new Token("--moon-tech-glow", PaletteSwatch.TechGlow, 1f),
            new Token("--moon-text", PaletteSwatch.Cream, 1f),
            new Token("--moon-text-dim", PaletteSwatch.Cream, 0.74f),
            new Token("--moon-text-faint", PaletteSwatch.Cream, 0.46f),
            new Token("--moon-glass", PaletteSwatch.SkyTop, 0.84f),
            new Token("--moon-glass-edge", PaletteSwatch.DustLight, 0.16f),
            new Token("--moon-veil", PaletteSwatch.SkyTop, 0.42f),
            new Token("--moon-shadow", PaletteSwatch.SkyTop, 0.5f),
            new Token("--moon-track", PaletteSwatch.Cream, 0.16f),
            new Token("--moon-cream-glow", PaletteSwatch.Cream, 0.1f),
            new Token("--moon-amber-soft", PaletteSwatch.WarmLamp, 0.16f),
            new Token("--moon-amber-edge", PaletteSwatch.WarmLamp, 0.6f),
            new Token("--moon-glow-soft", PaletteSwatch.TechGlow, 0.22f),
        };

        /// <summary>The token stylesheet (deterministic text).</summary>
        public static string BuildStyleSheet()
        {
            var builder = new StringBuilder();
            builder.Append("/* Generated by the UI/Theme builder from MoonProject.Art.Palette. Do not edit. */\n\n");
            builder.Append(":root {\n");
            foreach (Token token in Tokens)
            {
                Color32 color = Palette.Get(token.Swatch);
                builder.Append("    ").Append(token.Name).Append(": rgba(")
                    .Append(color.r.ToString(CultureInfo.InvariantCulture)).Append(", ")
                    .Append(color.g.ToString(CultureInfo.InvariantCulture)).Append(", ")
                    .Append(color.b.ToString(CultureInfo.InvariantCulture)).Append(", ")
                    .Append(token.Alpha.ToString("0.###", CultureInfo.InvariantCulture)).Append(");\n");
            }

            builder.Append("}\n");
            return builder.ToString();
        }

        private readonly struct Token
        {
            public Token(string name, PaletteSwatch swatch, float alpha)
            {
                Name = name;
                Swatch = swatch;
                Alpha = alpha;
            }

            public string Name { get; }

            public PaletteSwatch Swatch { get; }

            public float Alpha { get; }
        }
    }
}
