using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;
using MoonProject.Editor.Builders;

namespace MoonProject.UI.Editor
{
    /// <summary>
    /// Writes the UI theme: the palette token stylesheet (<see cref="ThemeTokens"/>), the runtime theme that imports
    /// Unity's default runtime theme plus the tokens, and the PanelSettings that render GameUI.uxml (scaled from a
    /// 1080p reference). Runs after the fonts, and re-imports GameUI.uss so its font references resolve.
    /// </summary>
    internal static class UiThemeBuilder
    {
        public const string BuilderPath = "UI/Theme";
        public const int BuilderOrder = 610;

        private const string StyleSheet = UiAssetPaths.SourceFolder + "/GameUI.uss";
        private static readonly Vector2Int ReferenceResolution = new Vector2Int(1920, 1080);
        private const float WidthHeightMatch = 0.5f;

        private const string ThemeText =
            "/* Generated by the UI/Theme builder. Do not edit. */\n" +
            "@import url(\"unity-theme://default\");\n" +
            "@import url(\"Palette.uss\");\n";

        [MoonBuilder(BuilderPath, BuilderOrder)]
        private static void Build()
        {
            var utf8 = new UTF8Encoding(false);
            GeneratedAssets.WriteFileIfChanged(UiAssetPaths.Palette, utf8.GetBytes(ThemeTokens.BuildStyleSheet()));
            GeneratedAssets.WriteFileIfChanged(UiAssetPaths.Theme, utf8.GetBytes(ThemeText));
            AssetDatabase.ImportAsset(StyleSheet, ImportAssetOptions.ForceUpdate);

            var theme = AssetDatabase.LoadAssetAtPath<ThemeStyleSheet>(UiAssetPaths.Theme);
            if (theme == null)
            {
                Debug.LogError($"{BuilderPath}: {UiAssetPaths.Theme} did not import as a theme style sheet.");
                return;
            }

            var panel = ScriptableObject.CreateInstance<PanelSettings>();
            panel.themeStyleSheet = theme;
            panel.scaleMode = PanelScaleMode.ScaleWithScreenSize;
            panel.referenceResolution = ReferenceResolution;
            panel.screenMatchMode = PanelScreenMatchMode.MatchWidthOrHeight;
            panel.match = WidthHeightMatch;
            panel.clearColor = false;
            GeneratedAssets.CreateOrReplace(panel, UiAssetPaths.PanelSettings);
            Debug.Log($"{BuilderPath}: wrote {UiAssetPaths.Palette}, {UiAssetPaths.Theme} and " +
                      UiAssetPaths.PanelSettings);
        }
    }
}
